postgres:
  image: postgres:latest
  ports:
    - "5432:5432"

django-tenants-test:
  build: .
  links:
    - postgres
  volumes:
    - .:/code
  command: ./run_tests.sh
  environment:
    DATABASE_HOST: postgres
  ports:
    - "8080:8080"
